jobs:
- job: 'Format with black'
  pool:
    vmImage: 'ubuntu-16.04' # other options: 'macOS-10.13', 'vs2017-win2016'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'

  - script: python -m pip install --upgrade pip setuptools wheel
    displayName: 'Install tools'

  - script: pip install black
    displayName: 'Install black'

  - script: black --check --diff umap
    displayName: 'Run black'

- job: 'Test & Coverage'
  dependsOn: 'Format with black'
  pool:
    vmImage: 'ubuntu-16.04' # other options: 'macOS-10.13', 'vs2017-win2016'
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'

  - script: python -m pip install --upgrade pip setuptools wheel
    displayName: 'Install tools'

  - script: pip install -r requirements.txt
    displayName: 'Install requirements'

  - script: |
      pip install pytest
      pip install pytest-cov
    displayName: 'Install pytest'

  - script: pip install -e .
    displayName: 'Install UMAP'

  - script: pytest umap --doctest-modules --junitxml=junit/test-results.xml --cov=umap --cov-report=xml --cov-report=html
    displayName: 'Run pytest'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '**/test-*.xml'
      failTaskOnFailedTests: true
      testRunTitle: 'Publish test results for $(python.version) Ubuntu-16.04'